### ISSUE TITLE
Open tree with items expanded

### ISSUE THREAD

**Issue by pietermartin** [PepsRyuu/virtual-scrolling-tree#3]
Hi,

This is not really an issue but I can not work out how to open the tree with certain nodes expanded.
Is this possible?

**Comment by PepsRyuu** [comment]
There actually isn't any way to at the moment, wasn't a use case I had at the time when I implemented this component. In theory it's quite difficult to implement, because the parent and its parents would need to be known along with the number of children for each of those parents and the node to be expanded.

I'll have a look later on this evening, and see what I can come up with. Seems like it would be a crucial feature to have for the tree. Thanks for bringing this up!

**Comment by pietermartin** [comment]
Great tx

**Comment by PepsRyuu** [comment]
I've released version 0.4.0 (https://github.com/PepsRyuu/virtual-scrolling-tree/commit/be046ce429207b0da0d0770dd7967dd62874387e) which should hopefully address this.

This contains two new functions: "expand" and "collapse". In order to use both of these, you need to pass the following object:

```
{
    "parent": <parent item id>,
    "id": <item id>,
    "children": <number of children in item>,
    "offset": <the position of this item relative to parent>
}
```
Do note that each of those properties are critical. If they're incorrect, the tree will get confused and will incorrectly render. Also if you want to expand a nested item, you must have already expanded the parent.

I've also updated the demo to include a demo of this feature under "Dynamic Expansions":

http://pepsryuu.github.io/demo/vst/

Let me know if this works for you! :)

**Comment by pietermartin** [comment]
Great thanks, I'll check it out tomorrow.

**Comment by pietermartin** [comment]
I tried it out and it is working but alas is seems slow down on multiple expansions.

To give you an an idea of my dataset. 
In total there are 2088 items in the data array. I implemented a filter box to search for items. The idea is to auto open the nodes to show the user the search hits.
A typical search that will be slow will try to expand 17 nodes. i.e. calling `expand({...})` 17 times. It slows down noticeably. About 3 seconds to expand all the nodes.

Also the rendering seems a tad off when scrolling fast with some incorrect nodes appearing and disappearing.

Expanding only one or two nodes are very fast.

**Comment by pietermartin** [comment]
Ok think some maybe most of it is my fault. I made my items like a proper tree to help implement the search and expand logic. Added a child array and map to each node. This probably makes `JSON.parse(JSON.stringify(output))` slow. I'll remove and test again.

**Comment by pietermartin** [comment]
The performance issue was mine.
Its working great, thanks.

**Comment by PepsRyuu** [comment]
Excellent! Can you clarify what the performance issue was? Would be good to know for future reference just incase someone encounters something similar.
